name: rlsimpy
channels:
  - defaults
dependencies:
  - joblib=0.14.1
  - jupyterlab=2.1.5
  - matplotlib=3.2.2
  - notebook=6.0.3
  - numpy=1.18.5
  - pandas=1.0.5
  - pip=20.1.1
  - python=3.7.6
  - pytorch=1.5.0
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - pip:
    - gym==0.17.1
    - simpy==4.0.1
